//! The event names and the URLs the shell owns that the app reads too, written beside
//! the ts-rs types as `shell.ts` so the app has one copy and a change reaches it on the next
//! test run.
use std::fmt::Write as _;
use std::path::PathBuf;

use sgf_app_lib::commands::{
    GAME_DATA_CHANGED_EVENT, GUIDE_URL, PROGRESS_EVENT, RELEASES_URL, UPDATE_PROGRESS_EVENT,
};

fn export_dir() -> PathBuf {
    std::env::var_os("TS_RS_EXPORT_DIR").map_or_else(
        || PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../src/generated"),
        PathBuf::from,
    )
}

#[test]
fn the_names_the_app_shares_are_exported_as_constants() {
    let mut out = String::from(
        "// This file was generated by sgf-app's constants test. Do not edit this file manually.\n\n",
    );
    for (doc, name, value) in [
        (
            "Emitted while a file loads or saves.",
            "PROGRESS_EVENT",
            PROGRESS_EVENT,
        ),
        (
            "Emitted when the game data is rebuilt, and when the auto-reload watcher pauses or resumes.",
            "GAME_DATA_CHANGED_EVENT",
            GAME_DATA_CHANGED_EVENT,
        ),
        (
            "Emitted while an update downloads.",
            "UPDATE_PROGRESS_EVENT",
            UPDATE_PROGRESS_EVENT,
        ),
        (
            "Where an update check would send the user, known without one.",
            "RELEASES_URL",
            RELEASES_URL,
        ),
        (
            "The user guide's front page, which the Help menu opens and the guide's pages are opened under.",
            "GUIDE_URL",
            GUIDE_URL,
        ),
    ] {
        writeln!(out, "/** {doc} */\nexport const {name} = {value:?};\n").unwrap();
    }
    let out = out.trim_end().to_owned() + "\n";

    let dir = export_dir();
    std::fs::create_dir_all(&dir).expect("the export directory");
    let path = dir.join("shell.ts");
    if std::fs::read_to_string(&path).ok().as_deref() != Some(out.as_str()) {
        std::fs::write(&path, &out).expect("write shell.ts");
    }
}
