[package]
name = "workshop-uploader"
version = "0.1.0"
edition = "2024"
publish = false

[workspace]

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
steamworks = { version = "0.13", features = ["raw-bindings"] }
ureq = "3"

[build-dependencies]
steamworks-sys = "0.13"
