//! The rules the core owns that the app reads too, written beside the ts-rs types as
//! `constants.ts` so the app has one copy and a change reaches it on the next test run.
use std::fmt::Write as _;
use std::path::PathBuf;

use sgf_core::NULL_ID;
use sgf_core::emit::DEFAULT_SYSTEM_HEIGHT;
use sgf_core::export::ScenarioProfile;
use sgf_core::export::policy::LCLUSTER_PREFIX;
use sgf_core::format::save::WHOLE_ENTRIES_FROM_MAJOR;
use sgf_core::format::scenario::fe_zone::{
    DEFAULT_DISTANCE, FE_ZONE_DISTANCES, FE_ZONE_EXTENT, FE_ZONE_RADIUS,
};
use sgf_core::format::scenario::paint::RESERVED_SEAT_NAMES;
use sgf_core::guides::L_CLUSTER;
use sgf_core::ops::{
    BELT_SCATTER, MOON_RING_FIRST, MOON_RING_STEP, OVERLAP_TOLERANCE, SPAWN_BUFFER,
    STORED_ORBIT_SLACK, SystemRadii,
};
use sgf_core::prepare::{PrepareChoice, PreparePreset, PrepareRow};
use sgf_core::views::Capabilities;

use crate::common;
use common::fixture::GRAMMAR;

/// The name `value` takes in JSON, without its quotes.
fn serde_name(value: &impl serde::Serialize) -> String {
    let json = serde_json::to_string(value).expect("serialise the value");
    json.trim_matches('"').to_owned()
}

/// `capabilities` as a TypeScript object literal, one field a line in declaration order.
fn capabilities(capabilities: Capabilities) -> String {
    let json = serde_json::to_string_pretty(&capabilities).expect("serialise the capabilities");
    json.lines()
        .map(|line| match line.trim_start().strip_prefix('"') {
            Some(field) => format!("  {},", field.replacen("\":", ":", 1).trim_end_matches(',')),
            None => line.to_owned(),
        })
        .collect::<Vec<_>>()
        .join("\n")
}

fn export_dir() -> PathBuf {
    std::env::var_os("TS_RS_EXPORT_DIR").map_or_else(
        || PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../app/src/generated"),
        PathBuf::from,
    )
}

#[test]
fn the_rules_the_app_shares_are_exported_as_constants() {
    let (x, y, radius) = L_CLUSTER;
    let distances: Vec<String> = FE_ZONE_DISTANCES.iter().map(u16::to_string).collect();
    let mut out = String::from(
        "// This file was generated by sgf-core's constants test. Do not edit this file manually.\n\nimport type { Capabilities } from \"./Capabilities\";\nimport type { PrepareChoice } from \"./PrepareChoice\";\nimport type { PreparePreset } from \"./PreparePreset\";\nimport type { PrepareRow } from \"./PrepareRow\";\nimport type { ScenarioProfile } from \"./ScenarioProfile\";\n\n",
    );
    let mut constant = |doc: &str, name: &str, value: String| {
        writeln!(out, "/** {doc} */\nexport const {name} = {value};\n").unwrap();
    };
    constant(
        "Where the game builds the L-Cluster for every galaxy size.",
        "L_CLUSTER",
        format!("{{ x: {x}, y: {y}, radius: {radius} }} as const"),
    );
    constant(
        "What an L-Cluster system's initializer, or one of its star flags, starts with.",
        "LCLUSTER_PREFIX",
        format!("{LCLUSTER_PREFIX:?}"),
    );
    constant(
        "How close the game lets a system it spawns stand to another.",
        "SPAWN_BUFFER",
        SPAWN_BUFFER.to_string(),
    );
    constant(
        "The id a save writes where an entity names none.",
        "NULL_ID",
        NULL_ID.to_string(),
    );
    constant(
        "The first major version whose saves take an added system.",
        "ADDED_SYSTEMS_FROM_MAJOR",
        WHOLE_ENTRIES_FROM_MAJOR.to_string(),
    );
    constant(
        "How far from its centre a fallen empire zone reaches.",
        "FE_ZONE_RADIUS",
        FE_ZONE_RADIUS.to_string(),
    );
    constant(
        "The distances the mod accepts between a zone's anchor and its centre.",
        "FE_ZONE_DISTANCES",
        format!("[{}] as const", distances.join(", ")),
    );
    constant(
        "Where a new zone is put: the nearest distance whose ring clears the anchor's own star.",
        "FE_ZONE_DEFAULT_DISTANCE",
        DEFAULT_DISTANCE.to_string(),
    );
    constant(
        "How far from the origin, on either axis, a zone's centre may lie.",
        "FE_ZONE_MAP_EXTENT",
        FE_ZONE_EXTENT.to_string(),
    );
    let SystemRadii {
        min_inner,
        inner_offset,
        outer_offset,
    } = SystemRadii::VANILLA;
    constant(
        "How vanilla sizes a system, for when no game data gives the install's defines.",
        "VANILLA_SYSTEM_RADII",
        format!(
            "{{ min_inner: {min_inner}, inner_offset: {inner_offset}, outer_offset: {outer_offset} }} as const"
        ),
    );
    constant(
        "The orbit of a planet's first moon.",
        "MOON_RING_FIRST",
        MOON_RING_FIRST.to_string(),
    );
    constant(
        "How much further out each moon ring after the first lies.",
        "MOON_RING_STEP",
        MOON_RING_STEP.to_string(),
    );
    constant(
        "How near, in units and in degrees, two bodies about one parent stand before they overlap.",
        "OVERLAP_TOLERANCE",
        OVERLAP_TOLERANCE.to_string(),
    );
    constant(
        "How far from its belt's radius an asteroid of that belt may lie.",
        "BELT_SCATTER",
        BELT_SCATTER.to_string(),
    );
    constant(
        "How far a body's point may stray from its stored orbit for the stored value to be drawn.",
        "STORED_ORBIT_SLACK",
        STORED_ORBIT_SLACK.to_string(),
    );
    constant(
        "The height above the galactic plane the game gives every system it generates.",
        "DEFAULT_SYSTEM_HEIGHT",
        DEFAULT_SYSTEM_HEIGHT.to_string(),
    );
    let names: Vec<String> = RESERVED_SEAT_NAMES
        .iter()
        .map(|n| format!("{n:?}"))
        .collect();
    constant(
        "Every name a Paint a Galaxy reserved seat can take, Latin letters then Greek.",
        "RESERVED_SEAT_NAMES",
        format!("[{}] as const", names.join(", ")),
    );
    for row in PrepareRow::ALL {
        assert_eq!(
            serde_json::to_string(&row).unwrap(),
            format!("{:?}", row.as_str())
        );
    }
    for choice in PrepareChoice::ALL {
        assert_eq!(
            serde_json::to_string(&choice).unwrap(),
            format!("{:?}", choice.as_str())
        );
    }
    let row_choices: Vec<String> = PrepareRow::ALL
        .iter()
        .map(|row| {
            let choices: Vec<String> = row
                .choices()
                .iter()
                .map(|c| format!("{:?}", c.as_str()))
                .collect();
            format!("  {}: [{}],", row.as_str(), choices.join(", "))
        })
        .collect();
    constant(
        "The choices each Prepare row offers, Keep first.",
        "PREPARE_ROW_CHOICES: Record<PrepareRow, readonly PrepareChoice[]>",
        format!("{{\n{}\n}}", row_choices.join("\n")),
    );
    let profiles: Vec<String> = [ScenarioProfile::Plain, ScenarioProfile::PaintAGalaxy]
        .into_iter()
        .map(|profile| {
            let presets: Vec<String> = PreparePreset::ALL
                .iter()
                .map(|preset| {
                    let choices: Vec<String> = preset
                        .choices(profile)
                        .iter()
                        .map(|c| format!("{}: {:?}", c.row.as_str(), c.choice.as_str()))
                        .collect();
                    format!("    {}: {{ {} }},", serde_name(preset), choices.join(", "))
                })
                .collect();
            format!(
                "  {}: {{\n{}\n  }},",
                serde_name(&profile),
                presets.join("\n")
            )
        })
        .collect();
    constant(
        "Each Prepare preset's choice for every row, on a map of each profile.",
        "PREPARE_PRESETS: Record<ScenarioProfile, Record<PreparePreset, Record<PrepareRow, PrepareChoice>>>",
        format!("{{\n{}\n}}", profiles.join("\n")),
    );
    constant(
        "What a Stellaris 4.x save supports.",
        "SAVE_CAPABILITIES: Capabilities",
        capabilities(Capabilities::of(common::open().doc())),
    );
    constant(
        "What a static galaxy scenario supports.",
        "SCENARIO_CAPABILITIES: Capabilities",
        capabilities(Capabilities::of(GRAMMAR.open().doc())),
    );
    let out = out.trim_end().to_owned() + "\n";

    let dir = export_dir();
    std::fs::create_dir_all(&dir).expect("the export directory");
    let path = dir.join("constants.ts");
    if std::fs::read_to_string(&path).ok().as_deref() != Some(out.as_str()) {
        std::fs::write(&path, &out).expect("write constants.ts");
    }
}
