//! The rules the core owns that the app reads too, written beside the ts-rs types as
//! `constants.ts` so the app has one copy and a change reaches it on the next test run.
use std::fmt::Write as _;
use std::path::PathBuf;

use sgf_core::export::policy::LCLUSTER_PREFIX;
use sgf_core::format::save::WHOLE_ENTRIES_FROM_MAJOR;
use sgf_core::format::scenario::fe_zone::{
    DEFAULT_DISTANCE, FE_ZONE_DISTANCES, FE_ZONE_EXTENT, FE_ZONE_RADIUS,
};
use sgf_core::guides::L_CLUSTER;
use sgf_core::ops::SPAWN_BUFFER;

fn export_dir() -> PathBuf {
    std::env::var_os("TS_RS_EXPORT_DIR").map_or_else(
        || PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../app/src/generated"),
        PathBuf::from,
    )
}

#[test]
fn the_rules_the_app_shares_are_exported_as_constants() {
    let (x, y, radius) = L_CLUSTER;
    let distances: Vec<String> = FE_ZONE_DISTANCES.iter().map(u16::to_string).collect();
    let mut out = String::from(
        "// This file was generated by sgf-core's constants test. Do not edit this file manually.\n\n",
    );
    let mut constant = |doc: &str, name: &str, value: String| {
        writeln!(out, "/** {doc} */\nexport const {name} = {value};\n").unwrap();
    };
    constant(
        "Where the game builds the L-Cluster for every galaxy size.",
        "L_CLUSTER",
        format!("{{ x: {x}, y: {y}, radius: {radius} }} as const"),
    );
    constant(
        "What an L-Cluster system's initializer, or one of its star flags, starts with.",
        "LCLUSTER_PREFIX",
        format!("{LCLUSTER_PREFIX:?}"),
    );
    constant(
        "How close the game lets a system it spawns stand to another.",
        "SPAWN_BUFFER",
        SPAWN_BUFFER.to_string(),
    );
    constant(
        "The first major version whose saves take an added system.",
        "ADDED_SYSTEMS_FROM_MAJOR",
        WHOLE_ENTRIES_FROM_MAJOR.to_string(),
    );
    constant(
        "How far from its centre a fallen empire zone reaches.",
        "FE_ZONE_RADIUS",
        FE_ZONE_RADIUS.to_string(),
    );
    constant(
        "The distances the mod accepts between a zone's anchor and its centre.",
        "FE_ZONE_DISTANCES",
        format!("[{}] as const", distances.join(", ")),
    );
    constant(
        "Where a new zone is put: the nearest distance whose ring clears the anchor's own star.",
        "FE_ZONE_DEFAULT_DISTANCE",
        DEFAULT_DISTANCE.to_string(),
    );
    constant(
        "How far from the origin, on either axis, a zone's centre may lie.",
        "FE_ZONE_MAP_EXTENT",
        FE_ZONE_EXTENT.to_string(),
    );
    let out = out.trim_end().to_owned() + "\n";

    let dir = export_dir();
    std::fs::create_dir_all(&dir).expect("the export directory");
    let path = dir.join("constants.ts");
    if std::fs::read_to_string(&path).ok().as_deref() != Some(out.as_str()) {
        std::fs::write(&path, &out).expect("write constants.ts");
    }
}
